In [1]:
# 패키지 업로드
import torch
import numpy as np
import pandas as pd

# 함수 생성
def mytranspose(x):
    if isinstance(x, np.ndarray):
        return x.T
    elif isinstance(x, pd.DataFrame):
        return x.transpose()
    elif isinstance(x, torch.Tensor):
        return x.clone() if x.ndim == 1 else x.t().clone()
    else:
        raise TypeError("지원하지 않는 타입입니다.")


In [2]:
# 테스트 데이터 준비
D = np.array([1, 2, 3, 4])
E = np.array(['red', 'white', 'red', np.nan])  # 문자열과 NaN 포함
F = np.array([True, True, True, False])
np_array = np.array([[1, 2], [3, 4]])


test_dict = {
    0: np.array([[1, 2, 3],
                 [4, 5, 6]]),
    1: np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8],
                 [9, 10]]),             # 5×2
    2: np.empty((0, 0)),                # 빈 행렬
    3: np.array([[1, 2]]),              # 1×2
    4: np.array([[1], [2]]),            # 2×1
    5: np.array([1, 2, np.nan, 3]),     # 1-D 벡터, NaN 포함
    6: np.array([np.nan]),              # 1-D 벡터 (NaN 하나)
    7: np.array([]),                    # 빈 벡터
    8: pd.DataFrame({"d": D, "e": E, "f": F}),
    "tensor": torch.tensor(np_array)
}

# 출력 함수
def show_before_after(label, obj):
    print(f"{'='*8}  {label}  {'='*8}")
    print("Before:")
    print(obj, "\n")
    print("After (mytranspose):")
    print(mytranspose(obj), "\n")

# 반복 실행
numeric_keys   = sorted(k for k in test_dict if isinstance(k, int))
non_numeric_keys = [k for k in test_dict if not isinstance(k, int)]

for key in numeric_keys + non_numeric_keys:
    show_before_after(key, test_dict[key])


========  0  ========
Before:
[[1 2 3]
 [4 5 6]] 

After (mytranspose):
[[1 4]
 [2 5]
 [3 6]] 

========  1  ========
Before:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

After (mytranspose):
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]] 

========  2  ========
Before:
[] 

After (mytranspose):
[] 

========  3  ========
Before:
[[1 2]] 

After (mytranspose):
[[1]
 [2]] 

========  4  ========
Before:
[[1]
 [2]] 

After (mytranspose):
[[1 2]] 

========  5  ========
Before:
[ 1.  2. nan  3.] 

After (mytranspose):
[ 1.  2. nan  3.] 

========  6  ========
Before:
[nan] 

After (mytranspose):
[nan] 

========  7  ========
Before:
[] 

After (mytranspose):
[] 

========  8  ========
Before:
   d      e      f
0  1    red   True
1  2  white   True
2  3    red   True
3  4    nan  False 

After (mytranspose):
      0      1     2      3
d     1      2     3      4
e   red  white   red    nan
f  True   True  True  False 

========  tensor  ========
Before:
tensor([[1, 2],
        [3, 4]]) 

After 